apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: v1je9g0hy-python
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: v1je9g0hy-python 
  name: v1je9g0hy-python
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: v1je9g0hy-python 
